//! Snitchwatch Tauri shell entry point.
//!
//! Order of operations (do not reorder without thinking about why):
//!   1. install panic hook FIRST so any panic during startup is captured
//!   2. init tracing → file appender at $XDG_STATE_HOME/snitchwatch/bridge.log
//!   3. build a multi-thread tokio runtime
//!   4. spawn the in-process bridge runtime; capture tray_rx + notice_rx
//!   5. build the Tauri application with the autostart plugin + commands
//!   6. install the Tray on app setup, spawn the Notifier task
//!   7. block on Tauri's run loop; on shutdown, abort the bridge

// Bring `#[macro_export]`-ed command wrapper macros (generated by #[tauri::command]) into scope.
#[macro_use]
extern crate snitchwatch_tauri;

use snitchwatch_tauri::{
    bridge_runtime::{spawn_bridge_runtime, BridgeRuntimeConfig},
    commands::{
        detect_daemon_state_cmd, get_autostart_state, install_daemon_stub, open_crash_log,
        set_autostart, start_daemon_unit,
    },
    notifier::Notifier,
    panic_hook, paths,
    tray::Tray,
};
use tauri_plugin_autostart::MacosLauncher;
use tracing_subscriber::EnvFilter;

fn main() -> anyhow::Result<()> {
    // 1. Panic hook first — captures any startup panic to crash.log.
    panic_hook::install(paths::crash_log_path());

    // 2. Tracing → rolling-never file appender in the XDG state dir.
    let log_dir = paths::state_dir();
    std::fs::create_dir_all(&log_dir).ok();
    let file_appender = tracing_appender::rolling::never(&log_dir, "bridge.log");
    let (non_blocking, _guard) = tracing_appender::non_blocking(file_appender);
    tracing_subscriber::fmt()
        .with_env_filter(EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()))
        .with_writer(non_blocking)
        .with_ansi(false)
        .json()
        .init();

    tracing::info!("snitchwatch-tauri starting");

    // 3. Multi-thread tokio runtime — Tauri runs its own event loop, so we
    //    create the runtime explicitly rather than using #[tokio::main].
    let runtime = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()?;

    // 4. Spawn the in-process bridge; extract the channel receivers before
    //    moving anything into Tauri closures.
    let bridge_runtime =
        runtime.block_on(async { spawn_bridge_runtime(BridgeRuntimeConfig::default()).await })?;

    let tray_rx = bridge_runtime.tray_rx().clone();
    let notice_rx = bridge_runtime.notice_rx();
    // The webview can't dial the bridge's Unix socket directly (WebKitGTK
    // has no such API — see `loopback_proxy`), and the loopback TCP proxy
    // it does dial requires callers to already know this token before it
    // will forward anything to `/stream`. Injecting it via an
    // `initialization_script` (below) is the only channel that's both
    // guaranteed to run before `web/js/app.js`'s first WS connection
    // attempt and invisible to any other local process — never sent over
    // the network, never written to a file or env var another process
    // could read.
    let ws_token = bridge_runtime.bridge.ws_token.as_str().to_string();

    // Spawn the notifier task on the tokio runtime before entering the Tauri loop.
    runtime.spawn(async move {
        Notifier::new().run(notice_rx).await;
    });

    // 5–6. Build and run the Tauri application.
    tauri::Builder::default()
        .plugin(tauri_plugin_autostart::init(
            MacosLauncher::LaunchAgent,
            None,
        ))
        .invoke_handler(tauri::generate_handler![
            detect_daemon_state_cmd,
            get_autostart_state,
            set_autostart,
            install_daemon_stub,
            start_daemon_unit,
            open_crash_log,
        ])
        .setup(move |app| {
            let handle = app.handle().clone();
            Tray::install(&handle, tray_rx)?;
            tracing::info!("tray installed");

            // Built programmatically (not declared in tauri.conf.json)
            // specifically so `ws_token` — generated fresh per launch — can
            // be injected via `initialization_script`. Tauri guarantees
            // this script runs before any page script, so
            // `window.__SNITCHWATCH_TOKEN__` is set before `app.js`
            // constructs its first WebSocket URL.
            let init_script = format!(
                "window.__SNITCHWATCH_TOKEN__ = {};",
                serde_json::to_string(&ws_token).expect("token string always serializes")
            );
            tauri::WebviewWindowBuilder::new(
                app,
                "main",
                tauri::WebviewUrl::External(
                    "http://127.0.0.1:3031/"
                        .parse()
                        .expect("hardcoded loopback URL is always valid"),
                ),
            )
            .title("Snitchwatch")
            .inner_size(1100.0, 720.0)
            .min_inner_size(800.0, 540.0)
            .resizable(true)
            .fullscreen(false)
            .initialization_script(&init_script)
            .build()?;

            Ok(())
        })
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                window.hide().ok();
                api.prevent_close();
            }
        })
        .run(tauri::generate_context!())?;

    // 7. Tauri run loop exited — shut down the bridge cleanly.
    bridge_runtime.shutdown();
    Ok(())
}
